#!/usr/bin/env bash
#read, IFS, Tell a Story about /etc/passwd


while IFS=: read -r username pass uid gid uid_info home_dir cmd_shell;
do
    echo "The user $username is part of the $gid gang, lives in $home_dir and rides $cmd_shell. $uid's place is protected by the passcode $pass, more info about the user here: $uid_info"
done < /etc/passwd
