#!/usr/bin/env bash
#Script That Prints "Best Schhol" 10 times but in 4th and 8th


i=1

while [ "$i" -lt 9 ];
do
    echo "Best School"
    ((i++))

    if [ "$i" -eq 4 ];
    then
        echo "bad luck"
    
    elif [ "$i" -eq 7 ];
    then
        echo "good luck"
    fi
done
