#!/usr/bin/env bash
#Scripts that prints from 1 to 20 with "case" statement

i=1

while [ "$i" -le 20 ];
do
    case $i in
        4)
            echo -e "4\nbad luck from China";;
        9)
            echo -e "9\nbad luck from Japan";;
        17)
            echo -e "17\nbad luck from Italy";;
        *)
            echo "$i";;
    esac
    ((i++))
done
