#!/usr/bin/env bash
#Conditions for files operators


filename="school"

if [ -e "$filename" ];
then
    echo "school file exists"

    if [ -s "$filename" ];
    then
        echo "school file is not empty"
    elif [ ! -s "$filename" ];
    then
        echo "school file is empty"
    fi

    if [ -f "$filename" ];
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
